### ISSUE TITLE
Request for License Change to GPLv2

### ISSUE THREAD

**Issue by harshu4** [Openmesh-Network/core#6]
**Request:**
We kindly request all contributors to respond to this issue with one of the following:
- **ack**: I approve the license change to GPLv2.
- **nack**: I do not approve the license change to GPLv2.

**Response Deadline:**
Please respond by 14/07/2024. If no response is received by then, it will be assumed that you approve ("ack") of the license change.

Thank you for your attention to this matter.

cc: @dowdt @classmateada @rajathkotyal  @harrys522 @harshu4

**Comment by harrys522** [comment]
ack

**Comment by rajathkotyal** [comment]
ack

**Comment by dowdt** [comment]
ack

**Comment by realadahe** [comment]
ack

**Comment by harshu4** [comment]
Ack

**Comment by dowdt** [comment]
All contributors acknowledged. Changing license.
![image](https://github.com/user-attachments/assets/0a1073af-015b-4747-9dde-01098e8fbe21)
